import React, { useState } from 'react';
import { X, AlertCircle, CheckCircle2 } from 'lucide-react';

const GithubIcon = ({ size = 24, className = '' }) => (
  <svg 
    xmlns="http://www.w3.org/2000/svg" 
    width={size} 
    height={size} 
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="2" 
    strokeLinecap="round" 
    strokeLinejoin="round" 
    className={className}
  >
    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
    <path d="M9 18c-4.51 2-5-2-7-2" />
  </svg>
);

interface GitHubSyncModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
}

export default function GitHubSyncModal({ isOpen, onClose, projectId }: GitHubSyncModalProps) {
  const [repoName, setRepoName] = useState("");
  const [description, setDescription] = useState("");
  const [visibility, setVisibility] = useState<"private" | "public">("private");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!repoName.trim()) {
      setError("Repository name is required.");
      return;
    }

    setIsSubmitting(true);
    setError(null);
    setSuccess(null);

    try {
      const apiUrl = (process.env.NEXT_PUBLIC_WS_URL || "ws://localhost:8001").replace('wss://', 'https://').replace('ws://', 'http://');
      const res = await fetch(`${apiUrl}/api/projects/${projectId}/github`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          repo_name: repoName.trim(),
          description: description.trim(),
          visibility
        })
      });

      const data = await res.json();
      if (!res.ok || data.error) {
        throw new Error(data.error || "Failed to sync to GitHub");
      }

      setSuccess(data.message || "Successfully synced to GitHub!");
      setTimeout(() => {
        onClose();
        setSuccess(null);
        setRepoName("");
        setDescription("");
      }, 2000);

    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-[#1e1e24] border border-[#2a2a35] rounded-xl shadow-2xl w-full max-w-md overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="flex items-center justify-between p-4 border-b border-[#2a2a35]">
          <h2 className="text-lg font-semibold text-white flex items-center gap-2">
            <GithubIcon size={18} />
            Sync to GitHub
          </h2>
          <button 
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-4 space-y-4">
          {error && (
            <div className="bg-red-500/10 border border-red-500/50 text-red-400 p-3 rounded-md text-sm flex items-start gap-2">
              <AlertCircle size={16} className="mt-0.5 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {success && (
            <div className="bg-green-500/10 border border-green-500/50 text-green-400 p-3 rounded-md text-sm flex items-center gap-2">
              <CheckCircle2 size={16} />
              <span>{success}</span>
            </div>
          )}

          <div className="space-y-1.5">
            <label className="text-sm font-medium text-gray-300">New repository name</label>
            <input 
              type="text" 
              value={repoName}
              onChange={(e) => setRepoName(e.target.value)}
              className="w-full bg-[#151518] border border-[#2a2a35] text-white rounded-md px-3 py-2 text-sm focus:outline-none focus:border-[#4a4a55] transition-colors"
              placeholder="my-awesome-project"
            />
          </div>

          <div className="space-y-1.5">
            <label className="text-sm font-medium text-gray-300">New repository description</label>
            <input 
              type="text" 
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full bg-[#151518] border border-[#2a2a35] text-white rounded-md px-3 py-2 text-sm focus:outline-none focus:border-[#4a4a55] transition-colors"
              placeholder="Generated by AgentForge"
            />
          </div>

          <div className="space-y-3 pt-2">
            <p className="text-sm font-medium text-gray-300">Visibility</p>
            
            <label className="flex items-start gap-3 cursor-pointer group">
              <div className="relative flex items-center justify-center w-5 h-5 mt-0.5">
                <input 
                  type="radio" 
                  name="visibility" 
                  value="private"
                  checked={visibility === "private"}
                  onChange={() => setVisibility("private")}
                  className="peer sr-only"
                />
                <div className="w-5 h-5 rounded-full border-2 border-gray-500 peer-checked:border-white transition-colors"></div>
                <div className="absolute w-2.5 h-2.5 rounded-full bg-white opacity-0 peer-checked:opacity-100 transition-opacity"></div>
              </div>
              <div>
                <p className="text-sm font-medium text-white">Private</p>
                <p className="text-xs text-gray-400">Only you can access this repo on GitHub.com</p>
              </div>
            </label>

            <label className="flex items-start gap-3 cursor-pointer group">
              <div className="relative flex items-center justify-center w-5 h-5 mt-0.5">
                <input 
                  type="radio" 
                  name="visibility" 
                  value="public"
                  checked={visibility === "public"}
                  onChange={() => setVisibility("public")}
                  className="peer sr-only"
                />
                <div className="w-5 h-5 rounded-full border-2 border-gray-500 peer-checked:border-white transition-colors"></div>
                <div className="absolute w-2.5 h-2.5 rounded-full bg-white opacity-0 peer-checked:opacity-100 transition-opacity"></div>
              </div>
              <div>
                <p className="text-sm font-medium text-white">Public</p>
                <p className="text-xs text-gray-400">This repo will be discoverable by everyone on GitHub.com</p>
              </div>
            </label>
          </div>

          <div className="pt-4">
            <button
              type="submit"
              disabled={isSubmitting || !repoName.trim()}
              className="w-full bg-[#2a2a35] hover:bg-[#3a3a45] disabled:bg-[#1a1a20] disabled:text-gray-500 disabled:cursor-not-allowed text-white font-medium py-2 px-4 rounded-md transition-colors flex items-center justify-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                  Creating...
                </>
              ) : (
                "Create GitHub repository"
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
